### ISSUE TITLE
mouse accel patch not working on my setup

### ISSUE THREAD

**Issue by qsxcv** [AWilliams17/Halo-CE-Mouse-Tool#2]
Unfortunately it seems that the patch (latest release version) for mouse acceleration is not working on my machine. I am running windows 7 64bit with halo pc patched to 1.10.

Possible related is that if I "write to memory" in the main menu and then try to start a game, there is an exception with the following info:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	halo.exe
  Application Version:	1.0.10.621
  Application Timestamp:	53726852
  Fault Module Name:	halo.exe
  Fault Module Version:	1.0.10.621
  Fault Module Timestamp:	53726852
  Exception Code:	c0000005
  Exception Offset:	000963c6
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033

**Comment by AWilliams17** [comment]
Howdy,

Exception code c0000005 is an Access Violation, meaning the program didn't have access to the memory of Halo.

That, or the program is attempting to write to a completely invalid area of memory, which shouldn't be happening. If that is the case, then this will require further looking into.

For now though, assuming it's the first case, have you attempted running the tool as an administrator? Was Halo running as an administrator, but not the tool? If you wish to run Halo as an administrator, the tool must also be run as administrator along side it. If Halo isn't run as an administrator, you still need to run the tool as admin.

Finally, you say Halo PC, are you referring to normal Halo, or Custom Edition?

**Comment by qsxcv** [comment]
I am running normal Halo, not custom edition.

I've ran the tool as admin, but it still doesn't seem to affect mouse control at all. I've set the x/y sensitivity to 5/1 to make it really obvious if the patch takes effect.

If I press F1 after I am in campaign, then quit to main menu, then try to go back into campaign, I get the same exception crash.

edit:
On my computer:
For halo custom edition, the patch works for changing sensitivity but it doesn't disable mouse accel.
For normal halo, the patch doesn't affect mouse control at all.

edit2:
disabling mouse accel works for me with (my own compiled build of) Chimera. There, the code searches for the address of the memory to overwrite. I believe Mouse Tool hardcodes the address instead in MiscUtils.cs. Perhaps that's why things are less consistent across different systems and why it is not working for me?

**Comment by AWilliams17** [comment]
Normal Halo always gave me issues with the patch unfortunately. It's just really unstable on it. I could never figure out why. Sorry about that.

For Halo Custom Edition I've heard varying reports that it either does disable acceleration properly or it doesn't. I think it works on Chimera because I found the mouse acceleration address through Chimera and not normal CE.

The address in MiscUtils,cs is a static/global variable address, and viewing it in Cheat Engine it looks consistent across Halo CE and Chimera. I'm not sure what the deal there is.

Sorry I couldn't be more help, development on this has kind of stopped lately as I focus on other things.

**Comment by AWilliams17** [comment]
Normal Halo always gave me issues with the patch unfortunately. It's just really unstable on it. I could never figure out why. Sorry about that.
For Halo Custom Edition I've heard varying reports that it either does disable acceleration properly or it doesn't. I think it works on Chimera because I found the mouse acceleration address through Chimera and not normal CE.
The address in MiscUtils,cs is a pointer, and viewing it in Cheat Engine it looks consistent across Halo CE and Chimera. I'm not sure what the deal there is.
Sorry I couldn't be more help, development on this has kind of stopped lately as I focus on other things.
